parser: babel-eslint

env:
  browser: true
  commonjs: true
  es2020: true
  node: true

extends:
  - google
  - plugin:jsdoc/recommended

parserOptions:
  ecmaVersion: 11
  # sourceType: module

ignorePatterns:
  - '**/dist/**'
  - '**/dev/**'
  - externs.js

rules:

  consistent-imports/default-variable-match-filename:
    - error
  
  jsdoc/check-tag-names:
    - error
    # Anyone can add needed Closure @annotations for ESLint here.
    - definedTags:
      - exportSymbol

  jsdoc/newline-after-description:
    - error
    - always

  jsdoc/require-file-overview: 
    - error
    - {
        tags: {
          fileoverview: {
            initialCommentsOnly: true,
            mustExist: true,
            preventDuplicates: true,
          },
          license: {
            initialCommentsOnly: true,
            mustExist: true,
            preventDuplicates: true,
          },
        }
      }

  require-jsdoc:
    - error
    - require:
        ClassDeclaration: true
        FunctionDeclaration: true
        MethodDefinition: true
        FunctionExpression: false
        ArrowFunctionExpression: false

  operator-linebreak:
    - error
    - after

  object-curly-spacing:
    - error
    - always

  eol-last:
    - error
    - always

plugins:
  - consistent-imports

settings:
  jsdoc:
    mode: closure
    tagNamePreference:
      # Disable @fileoverview -> @file replacement
      fileoverview: fileoverview
      file: fileoverview